#URL_TO_MONITOR="www.ieee.org"
URL_MONITOR_NAMESPACE="S2NEWTALHA_WH"
URL_MONITOR_NAME1A="ulr_availability"
URL_MONITOR_NAME1L="ulr_latency"
THRESHOLD_AVAIL=1
THRESHOLD_LATENCY=0.28
TABLE_NAME=""
def write_T(name):
    TABLE_NAME=name